### ISSUE TITLE
Reverse Fehler

### ISSUE THREAD

**Issue by jugendhacker** [demostat/demostat#12]
Wenn ich eine Demo mit dem Slug test aufrufe via /d/1/ erhalte ich diesen Fehler:
`Reverse for 'demo' with arguments '('test',)' not found. 1 pattern(s) tried: ['demo/(?P<date__year>[0-9]{4})/(?P<date__month>[0-9]{2})/(?P<date__day>[0-9]{2})/(?P<slug>[\\w-]+)/$']`

Ich vermute mal da fehlen auf Zeile 53 in der views.py von demostatapp irgendwie Argumente

**Comment by clerie** [comment]
//done
