### ISSUE TITLE
Reverse Fehler again

### ISSUE THREAD

**Issue by jugendhacker** [demostat/demostat#16]
`Reverse for 'demos_month' with arguments '('', '')' not found. 1 pattern(s) tried: ['demo/(?P<date__year>[0-9]{4})/(?P<date__month>[0-9]{2})/$']`

At the home path `/`

**Comment by frommMoritz** [comment]
Selbiger fehler ist bei mir auch aufgetreten, dies scheint dadurch verursacht zu werden dass keine Demos existieren. In Kombination zu #7 könnte hier auf Seite zum anlegen einer neuen Demo weitergeleitet werden wenn keine Demos existieren?

**Comment by jugendhacker** [comment]
Nein dieser Fehler tritt bei mir auch bei einer angelegten Demo auf...

**Comment by clerie** [comment]
Der Fehler trat auf, wenn folgender Filter kein Ergebnis lieferte:
```
Demo.objects.filter(date__gte=datetime.datetime(timezone.now().year, timezone.now().month, timezone.now().day)).order_by('date').first()
```
