### ISSUE TITLE
Konfiguration der Inhalte

### ISSUE THREAD

**Issue by clerie** [demostat/demostat#21]
Wär schön, wenn man sowas wie den Seitentitel usw. konfigurieren könnte.

Zwei Möglichkeiten:
- Über settings.py als globale Varaible
- Per Template

Sollen da dann auch Impressum usw rein?

Was sollen die Default Werte sein?

**Comment by frommMoritz** [comment]
Zwecks Vollständigkeit: 
in dem PR #26 bzw. dem commit 0a710e99406b8d4b9132e49a1eb51529f579ab8e wurde dieses Feature `Über settings.py als globale Varaible` für
 - Impressum
 - Datenschutzerklärung
 - Seitentitel

hinzugefügt
