### ISSUE TITLE
Organisation-View verschönern

### ISSUE THREAD

**Issue by clerie** [demostat/demostat#22]
Die Übersichtsseite muss dringend überarbeitet werden. Nicht nur, dass bestimmte Details nicht angezeigt werden, sondern auch, dass die angezeigten Demos ungefiltert sind und demnacht auch viel zu viele angezeigt werden können

**Comment by frommMoritz** [comment]
Wie ist das zu verstehen? Gehe ich recht in der Annahme dass hierbei die `Demos von xxx` Seite gemeint ist? Wenn ja, wie ist bestimmte Details konkret gemeint?
 - URL
 - Beschreibung
 

> sondern auch, dass die angezeigten Demos ungefiltert sind

Wie ist das zu verstehen?

**Comment by clerie** [comment]
Aktuell werden alle Demos angezeigt, die je eingetragen wurden. Das kann viel werden. Wir müssen uns überlegen, wie wir diese darstellen woll und welche Demos. Als Filter im Archiv oder nur Demos mit einer bestimmten Popularität...

**Comment by frommMoritz** [comment]
@clerie Kann das nachdem #25 gemerged wurde geschlossen werden?
