### ISSUE TITLE
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'

### ISSUE THREAD

**Issue by frommMoritz** [demostat/demostat#35]
Wenn `python3 manage.py migrate` ausgeführt wird und MySQL wie in der [README.me](https://github.com/demostat/demostat/blob/master/README.md) konfiguriert werde kommt folgende Warnung:
```
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/2.1/ref/databases/#mysql-sql-mode
```

Es kann seien dass dies erst mit #34 dazu kam, muss noch näher untersucht werden und ggf. die README.md in der live Sektion entsprechend angepasst werden.

Die Migrations werden jedoch problemlos ausgeführt!

**Comment by clerie** [comment]
Das ist mit 66f2f916d96ccad078514246844f25d4805b8ad8 passiert?

**Comment by frommMoritz** [comment]
Genau, das trat in der tag-refactor branch auf. Ich habe allerdings noch nict geprüft ob das auch in anderen Branches auftritt.

**Comment by clerie** [comment]
Hast du die neue Migration auf die alte DB ausgeführt oder die DB vorher geleert?
Hast du es mit einer Jungfräulichen DB getestet?

**Comment by frommMoritz** [comment]
Ich habe die Migrations auf eine Leere DB angewendet.

**Comment by clerie** [comment]
Probiere es nochmal auf eine neue DB

**Comment by clerie** [comment]
Hast du zwischenzeitlich etwas an der `settings.py` geändert?

Ansonsten können es ja nur Komplikationen mit dem `ManyToManyField` sein :thinking:

**Comment by frommMoritz** [comment]
Wenn ich die [hier](https://docs.djangoproject.com/en/2.1/ref/databases/#mysql-sql-mode) erwähnten änderungen in meiner Config vornehme funktioniert dies. 

> Ansonsten können e ja nur Komplikationen mit dem ManyToManyField sein :thinking: 

Wenn überhaupt indirekt. Es geht eher darum das Fehlerhaft eingefügte Daten einen Fehler anstatt warning werfen. 

> MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors.

Ich würde das einfach entsprechend an die README.md schreiben
