### ISSUE TITLE
Text anzeigen wenn keine Demos mit Filter vorhanden

### ISSUE THREAD

**Issue by frommMoritz** [demostat/demostat#36]
Wenn auf der gefilterten Archiv Seite (`/demo/?org=xx&tag=yy`)keine Demos angezeigt werden können sollte ein Text wie "Leider gibt es keine Passenden Demos" erscheinen

![Screenshot_2019-03-16 Alle Demos Demostat](https://user-images.githubusercontent.com/34239260/54481202-f145ed80-4831-11e9-85ee-7148ad16d948.png)

**Comment by clerie** [comment]
Ja, bitte :heart: 
Die können wir auch gleich noch in die Listenansicht übernehmen

**Comment by frommMoritz** [comment]
Dieser Fehler besteht weiter hin auf der Normalen Archiv Seite wenn ein Monat / Jahr ohne Demos über die URL eingegeben wurde.
