### ISSUE TITLE
OSM Karte über Cache Proxy

### ISSUE THREAD

**Issue by frommMoritz** [demostat/demostat#54]
Um die Last auf die OSM Server zu reduzieren sollten die OSM Karte auf Applikationsseite gecached werden.

https://wiki.openstreetmap.org/wiki/Tile_proxy

Die Frage: ein/mehrere Zentrale(r) Caching wie z.b. tiles.demostat.de welche für alle Installationen genutzt werden kann -> schlecht weil Zentralisiert, gut weil komplett unabhängige Software eingesetzt werden kann
Applikationsseitig etwas wie `/osmproxy/` welche das in Dateien cachet und bei bedarf Webserver seitig ebenfalls nochmal zusätzlich mit einem cache versehen werden **kann** -> schlecht weil in der Software relativ eingeschränkt, gut weil wäre teil der Applikation

**Comment by clerie** [comment]
Wir können eine Variable in der Settings Datei setzen, mit der dann die Standart URL überschrieben wird. Dann kann jeder seine Quelle aufsetzen und nutzen wie er will

**Comment by clerie** [comment]
Möglicherweise sollten wir dafür dann von den iFrames Abstand halten und unsere eigene Leaflet Bibliothek einbinden.

**Comment by frommMoritz** [comment]
> Wir können eine Variable in der Settings Datei setzen, mit der dann die Standart URL überschrieben wird. Dann kann jeder seine Quelle aufsetzen und nutzen wie er will

Das wäre sinvoll. Ggf. sogar mit platzhaltern in der Variable wo näheres wie marker position u.ä. angegeben werden kann. So legen wir uns nicht auf eine URL Format fest?

**Comment by clerie** [comment]
Das wird durch `str.format()` wohl kein Problem sein

**Comment by clerie** [comment]
https://pyformat.info/

**Comment by frommMoritz** [comment]
Inzwischen haben wir unter `https://{a-c}.tiles.demostat.de/` einen cache proxy. Durch die in #60 eingeführte Leafletmap kann dieser entsprechend eintragen werden
