### ISSUE TITLE
Falsche Zeitzone bei Sortierung Demoübersicht

### ISSUE THREAD

**Issue by clerie** [demostat/demostat#64]
![Screenshot_2019-03-22 Demos in Deutschland Demostat](https://user-images.githubusercontent.com/9381848/54865182-e1626800-4d61-11e9-90bf-8132be35c918.png)

**Comment by frommMoritz** [comment]
Welche Zeittone ist denn in der `settinsg.py` eingestellt? Und welcher Timestamp liegt in der Datenbank?
